services:
  postgres_database: # psql --user=postgres --host=database --port=5432
    image: postgres:latest
    hostname: postgres_database
    ports:
      - "5000:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: forum_aggregator
    networks:
      - app-net
  
  backend:
      build:
        context: .
        dockerfile: dockerfile
      hostname: backend
      ports:
        - "8000:80"
      networks:
        - app-net
      depends_on:
        - postgres_database

networks:
  app-net:
    driver: bridge