FROM mcr.microsoft.com/dotnet/sdk:6.0 as builder
WORKDIR /src
COPY . /src
RUN dotnet publish -c Release -o ./build

FROM mcr.microsoft.com/dotnet/aspnet:6.0
COPY --from=builder /src/build /build
WORKDIR /build
CMD "dotnet" "ForumAggregator.WebApi.dll"